### ISSUE TITLE
conformance feedback

### ISSUE THREAD

**Issue by ehuss** [CAD97/tinyc#2]
Some questions/feedback on the conformance library:

Would it be possible to use it without libtest?  I find the interface to be somewhat limiting.  For example, I'd like to pass in paths to a test runner (either files or directories), and have it automatically collect tests.  I'd also like to pass options (like `--edition=2015` or whatever).  I would also much prefer it to load the tests dynamically over using `include_str!`.

---
Similar to above, I'd like to explicitly have a test name and a separate description.  With the test name, you can pass it as a filter to only run matching tests, and descriptions are important since it isn't always obvious what a test is for.  The syntax I was thinking of would be:

```
=========
test name
Optional description, can span multiple lines.
options: foo,bar
=========

some code here

---

expected output
```

---

I was also thinking the tests could be driven by the structure of the filenames.  For example, the `expressions` directory would contain all the expressions, and each file could be named `Expression.tuple.test` or something like that.  This would allow the test driver to automatically choose the correct fragment of the language to parse by examining the filename (expressions in this case).   This way, you can easily segment the tests into sub-portions of the grammar (expressions, statements, patterns, types, etc.).

---

Would it be possible to add options to each test? For the rust grammar, I was intending that each test could be annotated with options to drive the parser.  For example:

```
dyn 2015
This is valid in 2015, but should be rejected in 2018.
options: 2015
========
dyn +
```

It could be a comma-separated list of options. Some other things would be nightly features, where not all parsers support all nightly features (and can also be asserted that stable parsers do not accept unstable syntax).

---

It's not clear to me how this will support superset comparison.  When comparing multiple rust parsers, some of them retain more information than others.  I'm not sure how flexible that will need to be.  At the very least, certain token fields will need to be ignored, but some will not.  I was originally thinking that there could be a syntax tree defined in Rust with annotations about what is optional, but I didn't get too far down that road.  Another idea is that parsers that do not support something could insert a "dummy span" (or token) in the output that would always compare successfully with any other span.

---

Will there be support for automatically generating the expected output?  What I would like to do is have something like rust's `--bless` or `insta review`.  It would be quite difficult to write tests without it.

**Comment by CAD97** [comment]
> Would it be possible to use it without libtest?

Actually, yes, it could definitely make sense to add a `harness=false` self runner. I still think libtest integration is the correct default, though.

> I would also much prefer it to load the tests dynamically over using `include_str!`.

A self runner would be able to load test cases dynamically. Until `#[test_case]` stabilizes, the libtest version requires generating `#[test]` functions at compile time.

> I'd like to explicitly have a test name and a separate description.

There's a name currently, but allowing a description just makes sense.

> I was also thinking the tests could be driven by the structure of the filenames.

This feels like something to be done at the tester level rather than the harness level. Just making up the attribute interface, it could look like:

```rust
#[conformance::test_case(exact, serde=serde_json, glob="tests/**/Expr.*.test")]
fn expr(stem: &str, source: &str) -> SyntaxNode<ast::Expression> {
    match stem {
        "Expr.Literal" => ast::Expr::of(parse(source, ast::Expr::Literal)),
        _ => unimplemented!("and so on")
    }
}

#[conformance::main]
static TESTS: &[conformance::TestCase] = &[expr];
```

**Comment by CAD97** [comment]
Actually, no, it wouldn't to get the stem and dispatch on that. Even if your test file is `Expr.MethodCall.test` or whatever, you still just want to parse it as an `Expr` because you need to test the "kind-of-expr" decision of the parsing code.

```rust
#[conformance::test_case(exact, serde=serde_json, glob="tests/**/Expr.*.test")]
fn expr(source: &str) -> Parse<ast::Expr> {
    ast::Expr::parse(source)
}

#[conformance::main]
static TESTS: &[conformance::TestCase] = &[expr];
```

The attributes would then emit code along the lines of

```rust
const expr: conformance::TestCase = conformance::TestCase {
    glob: "tests/**/Expr.*.test",
    f: |source: &str| -> Result<String, Box<dyn Error>> {
        #item
        #ser(&#fn_name(source))
    },
    norm: |source: &str| -> Result<String, Box<dyn Error>> {
        #ser(&#de::<#value>(source)?)
    }
}

static TESTS: &[conformance::TestCase] = &[expr];

fn main() {
    conformance::main(TESTS);
}
```

> Would it be possible to add options to each test?

Honestly, I think that should be handled at file granularity. I'd expect the rust-parser-battery to use some macro with the effect of

```rust
macro_rules! test_types {
    ( $($ty:ident),* $(,)? ) => {
        $(  #[conformance::test_case(exact, serde=json, glob=concat!("tests/**/", stringify!(#$ty), ".*.test"))]
            paste::item! {
                fn [<test_ $ty>](source: &str) -> impl serde::Serialize {
                    parse::<$ty>(source)
                }
            }
        )*
        #[conformance::main]
        static TESTS: &[conformance::TestCase] = &[$(paste::expr!([<test_ $ty>])*];
    }
}
```

Alternative file name conventions can be added to the macro along with their adjusted calling style.

> It's not clear to me how this will support superset comparison.

The main way is by defining a general data format in the [serde data model](https://serde.rs/data-model.html) that all parsers have to provide and target. That should probably be a fully Abstract Syntax Tree as opposed to saving more information.

The current matching mode is `exact`; I want to add something like [`assert-json-diff`'s `assert_json_include!`](https://crates.io/crates/assert-json-diff) to support testing that the produced output includes the test battery's example, but can contain more keys in structs and items in arrays.

I've been toying around with different ideas for a general tree diff for a while. I just need to figure out a decent algorithm for a minimizing diff, or give up on trying to give a good error in the failure case other than "failed match between {} and {}".

> Will there be support for automatically generating the expected output?

Yes, the standalone `harness=false` will definitely grow one of these. (The only reason I haven't added one yet for my own use of the library is a desire to keep the libtest-integrated version with no runtime peer dependencies.) What I've been doing so far is using IntelliJ's test runner window to get the unescaped diff between expected and actual.

(IntelliJ's test runner window is actually why I so wanted a solution that integrates with libtest; so integrations with libtest's (`--json`) output "just work" with conformance. We'll probably want to "pretend to be libtest" in terms of output format so integrations can work.)

**Comment by CAD97** [comment]
Closing as migrated to a standalone repository at https://github.com/CAD97/conformance/issues/1
